[package]
name = "rgb-core"
version = "0.10.0-beta.1"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "RGB Core Library: confidential & scalable smart contracts on Bitcoin & Lightning (consensus layer)"
repository = "https://github.com/RGB-WG/rgb-core"
homepage = "https://rgb.tech"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.66.0"
exclude = [".github"]

[lib]
name = "rgb"
crate-type = ["cdylib", "rlib"] # We need this for WASM

[[bin]]
name = "rgbcore-stl"
required-features = ["stl"]

[dependencies]
amplify = "~4.0.0-beta.18"
strict_encoding = "2.0.0-rc.1"
strict_types = "1.0.0-beta.3"
aluvm = { version = "0.10.0-alpha.1", features = ["std"] }
commit_verify = { version = "~0.10.0-beta.2", features = ["rand"] }
bp-core = { version = "~0.10.0-beta.1" }
secp256k1-zkp = { version = "~0.7.0", features = ["use-rand", "rand-std", "global-context"] }
baid58 = "~0.2.0"
mime = "0.3.16"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde", "stl"]
stl = ["strict_types/base64"]
serde = [
    "serde_crate",
    "amplify/serde",
    "strict_encoding/serde",
    "strict_types/serde",
    "commit_verify/serde",
    "bp-core/serde",
    "aluvm/serde",
    "secp256k1-zkp/use-serde"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding" }
strict_types = { git = "https://github.com/strict-types/strict-types" }
bp-core = { git = "https://github.com/BP-WG/bp-core" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm" }
