[package]
name = "rgb-core"
version = "0.10.0-alpha.1"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "RGB Core Library: consensus & verification for private & scalable client-validated smart contracts on Bitcoin & Lightning"
repository = "https://github.com/RGB-WG/rgb-core"
homepage = "https://rgb.tech"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib"]

[lib]
name = "rgb"
path = "src/lib.rs"

[dependencies]
amplify = "~4.0.0-beta.13"
strict_encoding = "2.0.0-beta.5"
strict_types = "1.0.0-beta.3"
aluvm = "0.10.0-alpha.1"
commit_verify = { version = "~0.10.0-beta.2", features = ["rand"] }
bp-core = { version = "~0.10.0-beta.1" }
secp256k1-zkp = { version = "~0.7.0", features = ["rand-std", "global-context"] }
baid58 = "~0.1.0"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde"]
serde = [
    "serde_crate",
    "amplify/serde",
    "strict_encoding/serde",
    "strict_types/serde",
    "commit_verify/serde",
    "bp-core/serde",
    "aluvm/serde",
    "secp256k1-zkp/serde"
]
